### ISSUE TITLE
APIClient host setting should be configurable

### ISSUE THREAD

**Issue by alax** [iron-io/iron_mq_node#26]
Preferably in a format like so:

    var imq = new iron_mq.Client({host: "mq-aws-us-east-1.iron.io", token: "MY_TOKEN", project_id: "MY_PROJECT_ID", queue_name: "MY_QUEUE"});

It may already be configurable, if so, can we get the docs updated?

**Comment by indrek-rajamets** [comment]
I had the same issue, but it seems, that setting an environment variable `IRON_HOST=mq-rackspace-lon.iron.io` works.

**Comment by alex-litvak** [comment]
@alax About host configuration you can find here:
http://dev.iron.io/mq/reference/configuration/#host_example
If you are using .NET lib, visit this page: 
https://github.com/iron-io/iron_dotnet/tree/v3#configuration

I think we should mension about host configuration not only here. Thanks for the note!

**Comment by Supermighty** [comment]
Update client library to allow for setting the `host` property in the Client constructor. 

```
var imq = new iron_mq.Client({host: "mq-aws-us-east-1.iron.io", token: "MY_TOKEN", project_id: "MY_PROJECT_ID", queue_name: "MY_QUEUE"});
```

**Comment by alex-litvak** [comment]
It is possible to set host in constructor. Here is a working code:

var iron_mq = require('iron_mq');
var imq = new iron_mq.Client({token: "YOUR_TOKEN", project_id: "YOUR_PROJECT_ID", host: "mq-aws-eu-west-1-1.iron.io"});
