### ISSUE TITLE
Error: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#34]
My code is running in Heroku and using this library to process IronMQ items.

When I do q.get() I sometimes get "getaddrinfo ENOTFOUND" errors. It happens intermittently, and rarely, but I've never had more than 1-2 days go by without this error popping up.

Does this mean the IronMQ infrastructure itself is down?

**Comment by GeoffreyPlitt** [comment]
And just now for the first time, I'm seeing:
q.get(): Error: {"msg":"Method {}GET not allowed"} 

So I'm not expecting a solution, just wondering if it's easy to tell if this is an issue in this libraries code, or the IronMQ infrastructure is really returning these errors.

I see nothing on https://status.iron.io/  to indicate the Iron.io team knows the infrastructure is having any errors.

**Comment by featalion** [comment]
Hi @GeoffreyPlitt, `getaddrinfo ENOTFOUND` looks like DNS issue. I never saw `{"msg":"Method {}GET not allowed"}` error before. Is it reproducible? Does it happen in the pair with first issue?

**Comment by GeoffreyPlitt** [comment]
Neither are reproducible, they happen intermittently for me, about 5% of the time. More today. I'm talking to the IronMQ team now, their HUD is giving Heroku error pages and "we're having an issue accessing queue information". So it does appear these errors are not the fault of this lib. I'll keep you posted, thanks for the quick reply!

**Comment by GeoffreyPlitt** [comment]
https://www.dropbox.com/s/lzxpiilb2be0uup/Screenshot%202015-01-28%2018.09.18.png?dl=0

**Comment by GeoffreyPlitt** [comment]
Closing
