### ISSUE TITLE
"Error: Not found" - does v3 use long polling?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#37]
I'm using v3 with an entry of "git://github.com/iron-io/iron_mq_node#v3" in package.json.

I do q.get({wait:30},...) to long-poll for 30 seconds. I'm getting immediate "Error: Not found" errors. In some scenarios my code may start polling on a queue before the first message is created on it (so before the queue exists) In the old service, that worked fine, there was a notion of "virtual queues", where it basically just returned no messages (if not long polling), or kept waiting (for long polling). I never received an error before on queue.get when a queue didn't exist yet, so this appears to be a new bug in v3.

Let me know what to do, thanks.

**Comment by featalion** [comment]
@GeoffreyPlitt, IronMQ v3 supports only create queue and post messages to nonexistent queues.

**Comment by GeoffreyPlitt** [comment]
Is that a typo, do you mean "existent" queues?

**Comment by featalion** [comment]
nope, I mean you can create new queue, or post to queue (default pull queue will be created in this case). All other operations on nonexistent queues are denied.

**Comment by GeoffreyPlitt** [comment]
gotcha, thanks
