### ISSUE TITLE
"options" should be "message"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#39]
At https://github.com/iron-io/iron_mq_node/blob/v3/lib/api_client.js#L182, shouldn't the "options" param be named "message" ? Took me a while to realize that.

**Comment by sunloverz** [comment]
Thanks! Fixing

**Comment by sunloverz** [comment]
It should contain `message_id` and `reservation_id`(`reservation_id` if message is reserved) 

From readme:
```js
var options = {message_id: 'xxxxxxxxx', reservation_id: 'xxxxxxxxx'};
queue.del(options, function(error, body) {});
```

**Comment by GeoffreyPlitt** [comment]
Can you update the documentation on https://github.com/iron-io/iron_mq_node to be accurate? I'm still a bit confused about the message-delete and message-release function signatures.

**Comment by GeoffreyPlitt** [comment]
Like why don't the release and delete functions use the same argument signature?

**Comment by featalion** [comment]
Documentation for v3 library is [there](https://github.com/iron-io/iron_mq_node/tree/v3). Signature of the function is `client.del(message_id, options, callback)` now. `reservation_id` is optional field to delete message, it is required only if message was reserved.

**Comment by GeoffreyPlitt** [comment]
Thanks
