### ISSUE TITLE
message_id is not defined (api_client.js)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#40]
ReferenceError: message_id is not defined
Possibly unhandled ReferenceError: message_id is not defined
    at APIClient.messagesDelete (/vagrant/node_modules/iron_clad/node_modules/iron_mq_node/lib/api_client.js:186:63)

message_id is used but not defined. this could have been caught by using a linter like JS Hint.

**Comment by sunloverz** [comment]
Thanks! Fixing

**Comment by sunloverz** [comment]
Opened a pull request https://github.com/iron-io/iron_mq_node/pull/41

**Comment by featalion** [comment]
hi @GeoffreyPlitt, pull request #41 is merged to v3 branch, please try it.

**Comment by GeoffreyPlitt** [comment]
Thanks!

**Comment by GeoffreyPlitt** [comment]
Verified.
