### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#42]
At iron_mq_node/lib/client.js:244 I'm getting the error above. The logic for the success case (error is null) tries to cb() with the following logic:

return cb(error, (options.n == null) || options.n === 1 ? body[0] : body);

I think the problem is, the API (or iron_core) is return body of "null" instead of empty array.

**Comment by featalion** [comment]
@GeoffreyPlitt I found, that it is regression in v3 API, we will fix it shortly.

**Comment by featalion** [comment]
Hi @GeoffreyPlitt , please, try [this branch with workaround](https://github.com/iron-io/iron_mq_node/tree/v3-messages-null-workaround).

**Comment by GeoffreyPlitt** [comment]
merged, thanks, closing.
