### ISSUE TITLE
Long polling on Get breaks Post

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#43]
I used the "wait" option (with a value of 30) for Get to do long polling, and what happens is posting messages suddenly starts taking 60 or 90 seconds before my callback is called.

Weird for 2 reasons:
- I'm not passing "wait" to Post, only to Get, yet Post behavior changes.
- Notice that this new delay in Post (60 or 90 seconds) is a multiple of my wait param.

I don't think anyone has tested long-polling with this library recently, because they would have noticed Post becomes unusable.

**Comment by featalion** [comment]
Do you use the same instance of `Client` object for concurrent poll/post messages? I assume it is possible reason of such behaviour.

**Comment by GeoffreyPlitt** [comment]
Yes I do. If using different clients will fix this, that wouldn't be hard for me to do for the short term. This could screw up other people later, so it should get fixed eventually. I guess I'll use separate clients for myself, up to you whether to keep this open or close it. Thanks.

**Comment by GeoffreyPlitt** [comment]
I'm re-opening this, because using separate clients does not fix the issue. I'm using a completely different client ( new iron_lib.Client(...)) for posting and another for Get, but Get with 30s long-poll parameter still makes Post wait 60 or 90 seconds. So this is a core bug somewhere in the module, perhaps in some request/connection pooling or something.

**Comment by featalion** [comment]
I will take a look into it today. Seems like non-async static client is used, but I am not sure...

**Comment by featalion** [comment]
Hm, I tried to make calls to IronMQ v3, and here is what I get:

```js
// node.js console
> var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b); });
undefined
> var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b); });
undefined
> POST
Error:  null
Body:  6114752232169687662
POLL
Error:  null
Body:  [ { id: '6114752232169687662',
    body: 'some-message-here',
    reservation_id: 'e7e4e9a803e5690fe5c9cb617e9c6ed3',
    reserved_count: 1 } ]
> var async = require('async');
> async.parallel([
... function() { q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b); }); },
... function() { q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b); }); }
... ], function(e) { console.log("ERROR!: ", e); });
undefined
> POST
Error:  null
Body:  6114752842055044169
POLL
Error:  null
Body:  [ { id: '6114752842055044169',
    body: 'some-message-here',
    reservation_id: 'ce09ff1f36930ecaf5343ab4de4bd0a9',
    reserved_count: 1 } ]
```

As you can see, in both cases, with plain calls and with `async` library, it works fine. Which version of Node.js you are using? Mine is v0.10.36. I found, that `request` library does not working with Node.js v0.12.x in some cases. See [request README](https://github.com/request/request) on GitHub for more information. I am not sure it is related ( :

**Comment by GeoffreyPlitt** [comment]
I'm using Node v0.10.32. Do you think going to v0.10.36 would solve it?

Also, can you attach timing measurements to your test above? I'm curious
how much time q.post() takes to finish (and fire the callback).



On Wed, Feb 11, 2015 at 4:55 PM, Yury Yantsevich <notifications@github.com>
wrote:

> Hm, I tried to make calls to IronMQ v3, and here is what I get:
>
> // node.js console> var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b); });undefined> var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b); });undefined> POST
> Error:  null
> Body:  6114752232169687662
> POLL
> Error:  null
> Body:  [ { id: '6114752232169687662',
>     body: 'some-message-here',
>     reservation_id: 'e7e4e9a803e5690fe5c9cb617e9c6ed3',
>     reserved_count: 1 } ]> var async = require('async');> async.parallel([
> ... function() { q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b); }); },
> ... function() { q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b); }); }
> ... ], function(e) { console.log("ERROR!: ", e); });undefined> POST
> Error:  null
> Body:  6114752842055044169
> POLL
> Error:  null
> Body:  [ { id: '6114752842055044169',
>     body: 'some-message-here',
>     reservation_id: 'ce09ff1f36930ecaf5343ab4de4bd0a9',
>     reserved_count: 1 } ]
>
> As you can see, in both cases, with plain calls and with async library,
> it works fine. Which version of Node.js you are using? Mine is v0.10.36. I
> found, that request library does not working with Node.js v0.12.x in some
> cases. See request README <https://github.com/request/request> on GitHub
> for more information. I am not sure it is related ( :
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iron-io/iron_mq_node/issues/43#issuecomment-73997769>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by featalion** [comment]
```js
> var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });
undefined
> var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });
undefined
> POST
Error:  null
Body:  6114758764814950909
Called at  Thu Feb 12 2015 02:06:46 GMT+0100 (CET)
POLL
Error:  null
Body:  [ { id: '6114758764814950909',
    body: 'some-message-here',
    reservation_id: '9d5edbb76af00a7f60f2a53a43cb3ef7',
    reserved_count: 1 } ]
Called at  Thu Feb 12 2015 02:06:48 GMT+0100 (CET)
```

I am not sure, that migration from v0.10.32 to v0.10.36 will help... but I just check the [changelog](http://nodejs.org/changelog.html) and found some fixes to `child_process`, which are possibly related to the issue.

**Comment by GeoffreyPlitt** [comment]
Your output doesn't tell me how long post() took, can you log the before
and after timestamps?

I'll try 0.10.36 in the meantime...

On Wed, Feb 11, 2015 at 5:11 PM, Yury Yantsevich <notifications@github.com>
wrote:

> > var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });undefined> var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });undefined> POST
> Error:  null
> Body:  6114758764814950909
> Called at  Thu Feb 12 2015 02:06:46 GMT+0100 (CET)
> POLL
> Error:  null
> Body:  [ { id: '6114758764814950909',
>     body: 'some-message-here',
>     reservation_id: '9d5edbb76af00a7f60f2a53a43cb3ef7',
>     reserved_count: 1 } ]
> Called at  Thu Feb 12 2015 02:06:48 GMT+0100 (CET)
>
> I am not sure, that migration from v0.10.32 to v0.10.36 will help... but I
> just check the changelog <http://nodejs.org/changelog.html> and found
> some fixes to child_process, which are possibly related to the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iron-io/iron_mq_node/issues/43#issuecomment-73999480>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by featalion** [comment]
```js
> Date();var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });
'Thu Feb 12 2015 02:39:06 GMT+0100 (CET)'
> Date();var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });
'Thu Feb 12 2015 02:39:23 GMT+0100 (CET)'
> POST
Error:  null
Body:  6114767174360925288
Called at  Thu Feb 12 2015 02:39:25 GMT+0100 (CET)
POLL
Error:  null
Body:  [ { id: '6114767174360925288',
    body: 'some-message-here',
    reservation_id: 'd2ad5b34a103370ea8d1573c1b4d69f8',
    reserved_count: 1 } ]
Called at  Thu Feb 12 2015 02:39:25 GMT+0100 (CET)
```

**Comment by GeoffreyPlitt** [comment]
Yeah your timings look fine. I just tried 0.10.36 and still get the
error. Let me create a minimal file that reproduces it and I'll post
that here.


On Wed, Feb 11, 2015 at 5:40 PM, Yury Yantsevich <notifications@github.com>
wrote:

> > Date();var outp = q.get({wait: 20, n: 10}, function(e, b) { console.log("POLL\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });'Thu Feb 12 2015 02:39:06 GMT+0100 (CET)'> Date();var outp = q.post('some-message-here', function(e, b) { console.log("POST\nError: ", e, "\nBody: ", b, "\nCalled at ", Date()); });'Thu Feb 12 2015 02:39:23 GMT+0100 (CET)'> POST
> Error:  null
> Body:  6114767174360925288
> Called at  Thu Feb 12 2015 02:39:25 GMT+0100 (CET)
> POLL
> Error:  null
> Body:  [ { id: '6114767174360925288',
>     body: 'some-message-here',
>     reservation_id: 'd2ad5b34a103370ea8d1573c1b4d69f8',
>     reserved_count: 1 } ]
> Called at  Thu Feb 12 2015 02:39:25 GMT+0100 (CET)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iron-io/iron_mq_node/issues/43#issuecomment-74002384>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by GeoffreyPlitt** [comment]
Darn, I can't reproduce this with a simple case. It must be something with other layers wrapped around it. I tried switching from a Promises thing (using process.nextTick()) to async using async.whilst, still didn't work. I guess we can close this, I'll just forget about long polling.
