### ISSUE TITLE
Post, Touch taking hundreds of seconds

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iron-io/iron_mq_node#47]
I'm using separate clients to do Post vs everything else (create/get/touch).

Still, I'm having a lot of situations where Post succeeds but only after 100s or 200s. Two hundred seconds is a very long time. The people at Iron support said the service itself is not seeing that kind of latency.

There is some bug in this library with connection-pooling or sockets or something causing this to happen.

How do I debug it?

**Comment by GeoffreyPlitt** [comment]
Same thing is happening with Touch. I'm now using 3 separate clients (one for Post, one for Touch, one for Workers) and still no relief from these huge latencies.

**Comment by featalion** [comment]
Could you, please, provide the code to reproduce the issue.
