### ISSUE TITLE
wait is not working for peek_n() method, it returns immediately 

### ISSUE THREAD

**Issue by pradeep-mishra** [iron-io/iron_mq_node#52]
queue.peek_n({
      n : 10,
      wait : 20
}, callback);

despite using wait property, callback return immediately with empty data.

**Comment by alex-litvak** [comment]
@pradeep-mishra 
Now the 'wait' property (long polling) available only with reservation:
queue.get_n({
n : 10,
wait : 20
}, callback);

**Comment by pradeep-mishra** [comment]
so, there is no way to get task without reserving, it with long poll option?

**Comment by alex-litvak** [comment]
Yes, there is no "wait" parameter in PEEK method:
http://dev.iron.io/mq/3/reference/api/#peek-messages
