### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by BradRuderman** [iron-io/iron_mq_node#54]
Not sure where the memory leak is, but there is something going on inside this module. I have created a repo here: https://github.com/BradRuderman/ironmemleak/blob/master/test.js

**Comment by BradRuderman** [comment]
Following up

**Comment by rdallman** [comment]
@featalion could you help brad debug please? any ideas?

**Comment by featalion** [comment]
I'll take a look.

**Comment by featalion** [comment]
@BradRuderman I have tested it under Mac OS X 10.10.4, Node.JS v0.12.4, and Ubuntu, Node.JS v0.10.25. `memwatch-next` reports nothing. Which operating system and Node.JS version you are using?

**Comment by BradRuderman** [comment]
@featalion  I went ahead and produced a repo. I used 
node v0.10.28
Debian GNU/Linux 7 \n \l
version 7.5

1) Start running this python script:
```
import time
from iron_mq import IronMQ

ironmq = IronMQ(
    token = "OOPjd5Pl5i7Kfltu5OebEAfcY10",
    project_id = "55a697286d8ad9000a0000dc"
)

while True:
  time.sleep(1)
  print("Putting message")
  ironmq.postMessage(queue_name="test", messages=[{
    "event" : "user_registered",
    "attributes" : {
        "eventName" : "User Registered",
        "created_at" : "2015-07-15T11:03:37.000-07:00",
        "first_name" : "Blah blah blah",
        "last_name" : "Blah Blah, llc",
        "email" : "blahblahblah@gmail.com",
        "city" : "San Francisco",
        "status" : "Active",
        "user_type" : "client",
    }
}])
```
2) run "node test.js" from the node repo 
3) run 
    while true; do ps efaux|grep test.js|egrep -v 'grep'|awk '{print $6}' >> ironmq_node_worker.txt; sleep 5; done

Note I ran the queue filler from a different server. Step #3 runs a command which prints the memory of the process to the file every 5 seconds. 

Here is the output of that file.
https://gist.github.com/BradRuderman/93579aa8701cf1916b34

At line 1085, I killed the queue filler process and you can see the memory consumption stabilizes. I am not sure if there is a memory leak or if the iron mq module requires a ton of memory to stabilize. It seems that it uses way more then it should!

**Comment by featalion** [comment]
I confirm, that memory usage from user-space perspective (`ps`, `top`, etc. command line tools) continuously growth. But `memleak-next` never fires 'leak' events. So that, I cannot prove, that memory leaks happen in our code or, even, in underlying modules. It is V8's job to ask operating system to allocate more memory or return the memory back.

**Comment by BradRuderman** [comment]
memleak-next, only looks for memory increases in 5 garbage collections. It still is alarming that this process's memory continues to grow

**Comment by BradRuderman** [comment]
@featalion To add a little bit more info, i ran this https://github.com/BradRuderman/ironmemleak/blob/noiron/test.js which removes the iron io modules. This process never goes above 12mb.

**Comment by spideron** [comment]
@featalion & @BradRuderman, I used another module that perform http outbound requests instead of ironmq and it stays stable. It seems that only requests that have data returned causing the memory growth. If we expose global.gc to the node app and force garbage collecting, the process remains stable.

**Comment by BradRuderman** [comment]
@featalion  looking for an update here! Current we are explicitly calling  global.gc(); to keep memory under control.

**Comment by featalion** [comment]
Hi all, thanks for the information. I will back to it ASAP.

**Comment by featalion** [comment]
> @featalion To add a little bit more info, i ran this https://github.com/BradRuderman/ironmemleak/blob/noiron/test.js which removes the iron io modules. This process never goes above 12mb.

It does nothing, except increment variable `i`. It does not use additional memory to operate. Client library generates and parses JSON strings, creates `Object`s, makes HTTP requests, etc. Thus it consumes memory.

Check out [this blog post](https://strongloop.com/strongblog/node-js-performance-garbage-collection/) on Node.JS garbage collection.

**Comment by BradRuderman** [comment]
@featalion Following up here. Are we confident there is no memory leak in this module? And that it simply is a problem with Node?

**Comment by BradRuderman** [comment]
@featalion following up, can we have a call to discuss this issue.

**Comment by treeder** [comment]
@BradRuderman email support@iron.io to setup a call.
