### ISSUE TITLE
 updating a queue not working

### ISSUE THREAD

**Issue by ppbntl19** [iron-io/iron_mq_node#63]
```
queue.update()  throw error.

/home/ubuntu/workspace/node_modules/iron_mq/lib/api_client.js:90
      return this.patch("/" + queue_name, options, function(error, response, b
                  ^
TypeError: Object #<APIClient> has no method 'patch'
    at APIClient.queuesUpdate (/home/ubuntu/workspace/node_modules/iron_mq/lib/api_client.js:90:19)
    at Client.update (/home/ubuntu/workspace/node_modules/iron_mq/lib/client.js:77:23)
```

**Comment by pouta** [comment]
Can confirm this is happening. iron_core_node does not implement the PATCH request type. After checking the history of the core it was never there.
I was planning to use this in my project but now I will consider different options since this project is dead.

**Comment by alex-litvak** [comment]
@ppbntl19 @pouta The fix is already published to npm

**Comment by pouta** [comment]
Great!! I thought the project was dead because no answer in this issue since Nov, 2015. Good job. Will test it tomorrow!

I hope my comment was helpful figuring it out.
