### ISSUE TITLE
[Error: Invalid project/token combination]

### ISSUE THREAD

**Issue by mdsadiq** [iron-io/iron_mq_node#69]
I am trying to run ironmq from docker and creating queue. But unable to send message. I am getting the following error
"[Error: Invalid project/token combination]"

Can you explain why?What is the issue ?

var imq = new iron_mq.Client({ token: "tokeidhere", project_id: "projectidhere", queue_name: "butler" });

queue.post("Welcome", function(error, body) {
        console.log("inside queue")
        if (error) {
            console.log(error)
        }
        if (body) {
            console.log(body)
        }
    });

ironmq installed from :  "git://github.com/iron-io/iron_mq_node.git#v3",

**Comment by alex-litvak** [comment]
@mdsadiq You should replace "tokeidhere" and "projectidhere" with real project_id and token.
